### ISSUE TITLE
Capture d'écran non-sourcée

### ISSUE THREAD

**Issue by Yovach** [Valwex/BlablaCore#2]
Bonjour,

J'apprécie grandement que tu viennes sur le serveur [https://www.blablaland.fun/](https://www.blablaland.fun/) pour prendre une capture d'écran du jeu et montrer à quoi ce projet à pour objectif. 
Mais je ne pense pas qu'avec des "Hello World !", tu arrives à faire tourner le jeu !

Si tu lis ce message, je voudrais que tu indiques la source de l'image :)

Bien à toi,
Yovach

**Comment by Valwex** [comment]
Bonjour Yovach,

Problème réglé.

Bonne journée.
